### ISSUE TITLE
usage problem

### ISSUE THREAD

**Issue by okm404** [EspressoCake/Self_Deletion_BOF#3]
![image](https://user-images.githubusercontent.com/42562811/143000430-fe9e89c8-95c8-49e1-95eb-7c8fd2b52640.png)
![image](https://user-images.githubusercontent.com/42562811/143000602-3f7cf763-a8c3-4317-88d5-08695443b6d4.png)
File not deleted
（Is this the way I use it wrong?）

**Comment by EspressoCake** [comment]
Hi @OkmOO, would you mind trying to do this with a `64-bit` artifact?  As it stands, there is an implementation of `NtClose`, meant only for these types of sessions.  In order to remediate this, use the `DFR` implementation of `CloseHandle`:
`DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI KERNEL32$CloseHandle (HANDLE);`
